[build]
  command = "npm run build:netlify"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  VALIDATION_STRICT = "false"
  NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT_LEVEL = "moderate"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/docs/*"
  to = "/:splat"
  status = 301

[[redirects]]
  from = "/docs"
  to = "/"
  status = 301